apifunc-register.go-Deleteの追加
SystemEngineeringTeam/HackU-2021-vol3 pull request #101
Opened 2022-02-20 15:12 UTC by k21139

2022-02-20 15:55 UTC, SuperTikuwa requested changes

2022-02-20 15:55 UTC, SuperTikuwa commented on backend/apifunc/register.go
> +	fmt.Println(event.OrganizerID)
これは何を取得してる？

2022-02-21 02:39 UTC, wind111-lang requested changes

2022-02-21 02:39 UTC, wind111-lang commented on backend/apifunc/register.go
> +	i, _ = strconv.Atoi(user["id"])
userから"id"は取れなかった気がする

2022-02-21 04:27 UTC, wind111-lang commented on backend/apifunc/register.go
> +	i, _ = strconv.Atoi(user["id"])
user(Firebase)から取れるのは "名前，画像URL, UID(userIDとは別)"

2022-02-21 07:10 UTC, SuperTikuwa requested changes
いまプルリク出してる，GetUserByFirebaseUIDという関数があるのでそれを使ってください(申し訳ない...)

2022-02-21 07:10 UTC, SuperTikuwa commented on backend/apifunc/register.go
> +	}
これは何を取得してるの？

2022-02-21 07:10 UTC, SuperTikuwa commented on backend/main.go
> +	router.HandleFunc("/user/{id}", apifunc.RegisterIdDeteleHandler)
- エンドポイントがそもそも違うし，メソッドも違うかも
- これだと/registerにPostリクエストを送ったときにどのハンドラ関数が実行されるかわからん
- /event/register/:idにリクエストが届くのでそれを使おう

2022-02-21 16:57 UTC, closed without merging